// Banner 图 technology 类型
export const techBannerImg1 = '/images/banner/technology/1.jpg';
export const techBannerImg2 = '/images/banner/technology/2.jpg';
export const techBannerImg3 = '/images/banner/technology/3.jpg';
export const techBannerImg4 = '/images/banner/technology/4.jpg';
export const techBannerImg5 = '/images/banner/technology/5.jpg';
export const techBannerImg6 = '/images/banner/technology/6.jpg';
export const techBannerImg7 = '/images/banner/technology/7.jpg';
export const techBannerImg8 = '/images/banner/technology/8.jpg';

// Banner 图 professional 类型
export const professionalBannerImg1 = '/images/banner/professional/1.jpg';
export const professionalBannerImg2 = '/images/banner/professional/2.jpg';
export const professionalBannerImg3 = '/images/banner/professional/3.jpg';
export const professionalBannerImg4 = '/images/banner/professional/4.jpg';
export const professionalBannerImg5 = '/images/banner/professional/5.jpg';
export const professionalBannerImg6 = '/images/banner/professional/6.jpg';
export const professionalBannerImg7 = '/images/banner/professional/7.jpg';
export const professionalBannerImg8 = '/images/banner/professional/8.jpg';

// Banner 图 minimalism 类型
export const minimalismBannerImg1 = '/images/banner/minimalism/1.jpg';
export const minimalismBannerImg2 = '/images/banner/minimalism/2.jpg';
export const minimalismBannerImg3 = '/images/banner/minimalism/3.jpg';
export const minimalismBannerImg4 = '/images/banner/minimalism/4.jpg';
export const minimalismBannerImg5 = '/images/banner/minimalism/5.jpg';
export const minimalismBannerImg6 = '/images/banner/minimalism/6.jpg';
export const minimalismBannerImg7 = '/images/banner/minimalism/7.jpg';
export const minimalismBannerImg8 = '/images/banner/minimalism/8.jpg';
